### ISSUE TITLE
Does not show up in UI

### ISSUE THREAD

**Issue by VOOM108** [ilian6806/rembgr#6]
I read the closed issue and tried to remove AGB (which never showed up in the UI as well) and also removed onnxruntime. 

It looks as if onnxruntime is installed again after removing the folder, but then I get errors like this: 

```
Error loading script: postprocessing_rembg.py
Traceback (most recent call last):
  File "C:\Users\***\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\***\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\***\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\scripts\postprocessing_rembg.py", line 5, in <module>
    import rembg
  File "C:\Users\***\stable-diffusion-webui\venv\lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "C:\Users\***\stable-diffusion-webui\venv\lib\site-packages\rembg\bg.py", line 21, in <module>
    from .session_base import BaseSession
  File "C:\Users\***\stable-diffusion-webui\venv\lib\site-packages\rembg\session_base.py", line 4, in <module>
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'
``` 

If I keep the existing onnruntime folder, I get no error messages, there is just nothing in the UI to activate rembgr.... The onnx already installed seems to be 1.13.1

**Comment by ilian6806** [comment]
Rembgr use rembg package that depends on onnxruntime, so it must be there. If extension exist in /extenstions dir and you dont see it in the UI it must be some kind of error. It is very strange if nothing was printed in the console... May be you can try it on fresh Web UI installation.

**Comment by VOOM108** [comment]
I was - after watching a video about this extension - expecting to find it under im2img and as a simple checkbox. What I do have is a menu under extras with different models like u2net. However, trying to use any of these models I get this: 

```
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=2160x2160 at 0x1B5A09B33D0>, None, '', '', True, 0, 4, 512, 512, True, 'None', 'None', 0, 0, 0, 0, 'u2net_human_seg', False, True, 240, 10, 10) {}
Traceback (most recent call last):
  File "C:\Users\****\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\****\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\****\stable-diffusion-webui\modules\postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "C:\Users\****\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "C:\Users\****\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\scripts\postprocessing_rembg.py", line 53, in process
    session=rembg.new_session(model),
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\rembg\session_factory.py", line 66, in new_session
    ort.InferenceSession(
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1069 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
```

**Comment by VOOM108** [comment]
Which is, what the other user had in the closed issue. However, the path to the solution there did not work for me.

**Comment by VOOM108** [comment]
Ok, so I deleted all folders in site-packages with onnx in the folder name. Then the installation of onnx by your extension installed 1.14.1 instead of 1.13.1 - and now it works... 

Maybe it would be helpful to provide a screenshot of where to find the setting after installing the extension... :)

**Comment by ilian6806** [comment]
I will, thank you :)
